version: "2"

services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - 8080
    environment:
      - VIRTUAL_HOST
      - VIRTUAL_PORT=8080
      - DB_HOST=mongo
      - SPECKLE_NAME="Speckle OSX Localhost"
      - SPECKLE_URL="http://127.0.0.1:8080/api/v1"
      - SPECKLE_SOCKET="http://127.0.0.1:8080/api/v1"
    links:
       - mongo:mongo
    depends_on:
       - mongo
    networks:
       - front
       - back
       - default
  mongo:
     image: mongo:latest
     volumes:
       - ./data/db:/data/db
     environment:
       - MONGO_INITDB_ROOT_USERNAME=reportsUser
       - MONGO_INITDB_ROOT_PASSWORD=password
       - MONGO_INITDB_DATABASE=speckle
     networks:
       - default
       - back
networks:
    front:
        external:
            name: "puffin_front"
    back:
        external:
            name: "puffin_back"
