version: "2"

services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_USER=reportsUser ## Your hosted mongo instance username
      - DB_PW=password ## Your password for the user
      - DB_HOST=127.0.0.1 ## The URL your db can be found at
      - DB_PORT=27017 ## The port your mongo is running on
      - SPECKLE_NAME="Speckle OSX Localhost"
      - SPECKLE_URL="http://127.0.0.1:8080/api/v1"
      - SPECKLE_SOCKET="http://127.0.0.1:8080/api/v1"
    links:
       - mongo:mongo
    depends_on:
       - mongo
  mongo:
     image: mongo:latest
     volumes:
       - ./data/db:/data/db
     ports:
       - "27017:27017"
     environment:
       - MONGO_INITDB_ROOT_USERNAME=reportsUser
       - MONGO_INITDB_ROOT_PASSWORD=password
       - MONGO_INITDB_DATABASE=speckle
